---
abstract: 'flexible RDFa parser'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-RDFa-Parser
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Carp: 0
  File::ShareDir: 0
  RDF::Trine: 0.112
  Storable: 0
  URI::Escape: 0
  URI::URL: 0
  XML::LibXML: 1.66
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-RDFa-Parser
  homepage: http://search.cpan.org/dist/RDF-RDFa-Parser/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/RDF-RDFa-Parser/
version: 1.00.002
