---
abstract: 'flexible RDFa parser'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Slurp: 0
  HTTP::Response: 0
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
keywords:
  - RDF
  - RDFa
  - 'Semantic Web'
  - HTML
  - XHTML
  - Atom
  - SVG
  - XML
  - OpenDocument
  - ODF
  - Metadata
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-RDFa-Parser
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  Archive::Zip: 0
requires:
  Carp: 0
  Data::Dumper: 0
  Data::UUID: 0
  File::ShareDir: 0
  File::Spec: 0
  File::Temp: 0
  HTML::HTML5::Parser: 0
  HTML::HTML5::Sanity: 0
  HTTP::Cache::Transparent: 0
  LWP::UserAgent: 0
  Module::Pluggable: 0
  RDF::Trine: 0.123
  Scalar::Util: 0
  Storable: 0
  URI::Escape: 0
  URI::URL: 0
  URI::file: 0
  XML::LibXML: 1.66
  XML::RegExp: 0
  common::sense: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-RDFa-Parser
  homepage: http://search.cpan.org/dist/RDF-RDFa-Parser/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/RDF-RDFa-Parser/
version: 1.093
