--- #YAML:1.0
name:               RDF-RDFa-Parser
version:            0.21
abstract:           RDFa parser using XML::LibXML.
author:
    - Toby Inkster <tai@g5n.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    RDF::Trine:   0.111
    URI::URL:     5
    XML::LibXML:  1.66
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
